language: go
sudo: false

go:
  - 1.10.3

before_install:
  - go get -u golang.org/x/vgo
  - go run ./patch-runtime/main.go

script:
  - make cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
